# Generated by Django 3.2.9 on 2021-12-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_ctasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CtaSettings',
        ),
    ]
