# Generated by Django 3.2.9 on 2021-12-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_ctasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CtaSettings',
        ),
    ]
